### ISSUE TITLE
meanT is broken

### ISSUE THREAD

**Issue by Atry** [deeplearning4j/nd4s#100]
See #97

**Comment by agibsonccc** [comment]
I told you what needed to happen on the pull request. Re submit if you want to try to apply the advice I gave you in my review.

**Comment by Atry** [comment]
This is a bug report

**Comment by agibsonccc** [comment]
That's fine then. Not sure why you submitted and referenced a pull request o_0. Are you submitting the bug report rather than the pull request because you don't want to make the changes I suggested or..?

**Comment by Atry** [comment]
It seems the library is not active maintained

**Comment by agibsonccc** [comment]
Nd4j is (see commit history). Nd4s is  a completely different library that just wraps nd4j.
 Nd4s needs work yes. Let's keep this on topic. If you aren't interested in helping, we will get to this when we have bandwidth. Right now we don't. Complaining doesn't help either of us right now. You don't have to use it.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4s/pull/103
