### ISSUE TITLE
nd4s build needs updating. Has issues with openblas

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4s#102]
Error:Error while importing SBT project:<br/>...<br/><pre>[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-android-arm.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-android-x86.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-armhf.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-ppc64le.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-x86.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-x86_64.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-macosx-x86_64.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-windows-x86.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-windows-x86_64.jar
[error] (*:ssExtractDependencies) coursier.ResolutionException: 9 not found
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-android-arm.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-android-x86.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-armhf.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-ppc64le.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-x86.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-linux-x86_64.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-macosx-x86_64.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-windows-x86.jar
[error]   /home/agibsonccc/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.19-1.3/openblas-platform-0.2.19-1.3-windows-x86_64.jar
[error] Total time: 298 s, completed Feb 28, 2017 5:19:02 PM</pre><br/>See complete log in <a href="/home/agibsonccc/.IntelliJIdea2016.3/system/log/sbt.last.log">/home/agibsonccc/.IntelliJIdea2016.3/system/log/sbt.last.log</a>

**Comment by agibsonccc** [comment]
Nevermind coursier just bad. I forgot it can't resolve classifiers.

**Comment by saudet** [comment]
See https://github.com/deeplearning4j/nd4j/issues/1366
