### ISSUE TITLE
java.util.List[java.lang.Float] is hard to convert to NDArray

### ISSUE THREAD

**Issue by borissmidt** [deeplearning4j/nd4s#111]
Since the type system implicitly shows java.lang.Float as Float. But when you call toArray it will give a compilation error.

My proposed solution add the following implicit conversions, here i replace null with the 0 value:
```
implicit def jfloatColl2INDArray(s:Seq[java.lang.Float]):FloatArray2INDArray = new FloatArray2INDArray(s.map(float =>{ Option(float).map(_.toFloat).getOrElse(0.0f)}))
```
If you find this an acceptable solution i will implement it and create a pull request.

**Comment by saudet** [comment]
Sounds good to me

**Comment by borissmidt** [comment]
I made a pull request :)

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5260
