### ISSUE TITLE
There is a bug in `CollectionLikeNDArray.existsRC`

### ISSUE THREAD

**Issue by letalvoj** [deeplearning4j/nd4s#120]
Check out [CollectionLikeNDArray.scala#L77](https://github.com/deeplearning4j/nd4s/blob/bf2ea7d5f829f0d3a61c11a0d8ba11ccc6e220dd/src/main/scala/org/nd4s/CollectionLikeNDArray.scala#L77). The condition is negated 😉 . I am updating the code in [#108](https://github.com/deeplearning4j/nd4s/issues/108) anyway. Thus I'll write breaking tests and fix it there.

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5262
