### ISSUE TITLE
[Feature]Allow to omit a part of submatrix indices range.

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4s#15]
Like NumPy.

```python
>>> x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>>> x[5:]
array([5, 6, 7, 8, 9])
```

http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

**Comment by taisukeoe** [comment]
I'm wondering two options of syntax:
```scala
val ndarray = (1f to 9f by 1).asNDArray(3,3)
//naive expression
ndarray(1->2,->)

//option 1
ndarray(1~>,->)

//option 2
ndarray(1-->,->)
```

Which do you like? > @agibsonccc

**Comment by agibsonccc** [comment]
option 2. tildes can be weird to type

**Comment by taisukeoe** [comment]
Thanks so much for your comment.
Finally I could find a way to use `5->` as NumPy use `5:`.
