### ISSUE TITLE
[Feature]Allow ellipsis to specify submatrix indices range

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4s#16]
Like NumPy.

While x is 3rd dimensional matrix, following two expression should be treated as same.
```python
x[...,0]
is the same as
x[:,:,0]
```

http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

In ns4j, since `...` cannot be valid expression in Scala,  it would be something like this? @agibsonccc 
```scala
x(--->,0)
is the same as
x(->,->,0)
```

**Comment by agibsonccc** [comment]
That'd be fine

**Comment by taisukeoe** [comment]
Thanks for your confirmation of syntax proposal!
I sent a PR to add it :)
