### ISSUE TITLE
nd4j-x86 causes test suite failures

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#22]
I replaced nd4j-jblas with nd4j-x86 in the test suite

 DSLSpec:
[info] DSL
[info] Exception encountered when attempting to run a suite with class name: org.nd4j.api.linalg.DSLSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
[info]   at org.nd4j.api.linalg.DSLSpec$$anonfun$1.apply$mcV$sp(DSLSpec.scala:37)
[info]   at org.nd4j.api.linalg.DSLSpec$$anonfun$1.apply(DSLSpec.scala:33)
[info]   at org.nd4j.api.linalg.DSLSpec$$anonfun$1.apply(DSLSpec.scala:33)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   ...
[info] RichNDArrayTest:
[info] org.nd4j.api.Implicits.RichNDArray
[info] Exception encountered when attempting to run a suite with class name: org.nd4j.api.RichNDArrayTest *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: org/bytedeco/javacpp/Pointer
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: org.bytedeco.javacpp.Pointer
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[info]   ...
[info] RichNDArraySpec:
[info] RichNDArray
[info] Exception encountered when attempting to run a suite with class name: org.nd4j.api.linalg.RichNDArraySpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
[info]   at org.nd4j.api.linalg.RichNDArraySpec$$anonfun$1.apply$mcV$sp(RichNDArraySpec.scala:34)
[info]   at org.nd4j.api.linalg.RichNDArraySpec$$anonfun$1.apply(RichNDArraySpec.scala:31)
[info]   at org.nd4j.api.linalg.RichNDArraySpec$$anonfun$1.apply(RichNDArraySpec.scala:31)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   ...
[info] Run completed in 379 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 3
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 3 SUITES ABORTED ***
[error] Error during tests:
[error]         org.nd4j.api.RichNDArrayTest
[error]         org.nd4j.api.linalg.DSLSpec
[error]         org.nd4j.api.linalg.RichNDArraySpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 21 s, completed Jul 20, 2015 12:19:54 AM

**Comment by agibsonccc** [comment]
so if nd4j-x86 is pulled in it has a dep on javacpp. Not sure why a ClassNotFound is being thrown here.
