### ISSUE TITLE
cumulative sum in nd4s

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#25]
It would be nice to have the cumulative sum in nd4s and have it also follow the range syntax "->". 
If possible it should return a singular double value. I would like to know if there's reason to continue supporting the return of INDArrays.

**Comment by taisukeoe** [comment]
> It would be nice to have the cumulative sum in nd4s and have it also follow the range syntax "->".  

Do you mean this syntax?
http://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html

> If possible it should return a singular double value.

Would you be more specific on this?

**Comment by rahulpalamuttam** [comment]
Here's what I had envisioned and what I'm dealing with currently
I have an INDArray and to obtain the sum of a block of elements elements I need to do this:

val block = SomeINDArray(5 -> 10, 0 ->20)
val sum : Double = block.sum(Integer.MAX_VALUE).getDouble(0)

ideally I would like to do this:

val block = SomeINDArray(5 -> 10, 0 -> 20)
val sum : Double = block.sum

cumsum seems to only get sums of sub-arrays along a particular axis.
We should be able to do that in the following way
val block = SomeINDArray(->, 0->20)
val sum : Double = block.sum

Let me know what you think.

**Comment by taisukeoe** [comment]
Thanks for your explanation.
It sounds reasonable for sum operation variation, while we should rethink methods name since `sum` or `cumsum` will collide with the same name methods in INDArray.
