### ISSUE TITLE
Elementwise masking

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#26]
It would be nice to extend the elementwise masking capability of INDArrays for RichNDArrays.

For example def :<=(other : Number) returns the matrix that results from doing an elementwise less than or equal to operation. Indices where the expression is false is 0, otherwise it remains the same as that in the matrix.

**Comment by taisukeoe** [comment]
Now you can elementwise masking like this.

```scala
val ndArray =
      Array(
        Array(1, 2, 3),
        Array(4, 5, 6),
        Array(7, 8, 9)
      ).toNDArray

ndArray.filter(_ > 3)

assert(filtered ==
      Array(
        Array(0, 0, 0),
        Array(4, 5, 6),
        Array(7, 8, 9)
      ).toNDArray)

val filterMasked = ndArray.filterBit(_ % 2 == 0)

assert(filterMasked ==
      Array(
        Array(0, 1, 0),
        Array(1, 0, 1),
        Array(0, 1, 0)
      ).toNDArray)
```

Since too many custom operators may spoil source code readability, I use `filter` function name as Scala Collection has similar one :).
