### ISSUE TITLE
nd4s slicing broken

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#27]
I get the following issue when running the nd4s  ExtractionTest/ RichNDArrayTest.

There seems to be an issue with the indexing.

RichNDArrayTest:
[info] org.nd4j.api.Implicits.RichNDArray
[info] - should provides forall checker *** FAILED ***
[info]   java.lang.IllegalArgumentException: Illegal index 9 derived from 3 with offset of 0 and stride of 3
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2972)
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3421)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$forall$extension$1$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(Implicits.scala:17)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$forall$extension$1.apply$mcV$sp(Implicits.scala:16)
[info]   at scala.util.control.Breaks.breakable(Breaks.scala:37)
[info]   at org.nd4j.api.Implicits$RichINDArray$.forall$extension(Implicits.scala:14)
[info]   at org.nd4j.api.Implicits$RichINDArray$.$greater$extension(Implicits.scala:25)
[info]   at org.nd4j.api.RichNDArrayTest$$anonfun$1.apply$mcV$sp(NDArrayExtractionTest.scala:13)
[info]   at org.nd4j.api.RichNDArrayTest$$anonfun$1.apply(NDArrayExtractionTest.scala:9)
[info]   ...
[info] - should be able to extract a part of 2d matrix *** FAILED ***
[info]   java.lang.IllegalArgumentException: Illegal index 12 derived from 4 with offset of 0 and stride of 3
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2972)
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3421)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$2.apply$mcDI$sp(Implicits.scala:62)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$2.apply(Implicits.scala:62)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$2.apply(Implicits.scala:62)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[info]   ...
[info] - should be able to extract a part of 3d matrix *** FAILED ***
[info]   java.lang.IllegalArgumentException: Illegal index 8 derived from 2 with offset of 0 and stride of 4
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2972)
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3421)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$2.apply$mcDI$sp(Implicits.scala:62)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$2.apply(Implicits.scala:62)
[info]   at org.nd4j.api.Implicits$RichINDArray$$anonfun$2.apply(Implicits.scala:62)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[info]   ...
[info] Run completed in 2 seconds, 134 milliseconds.
[info] Total number of tests run: 15
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 12, failed 3, canceled 0, ignored 0, pending 0
[info] *** 3 TESTS FAILED ***
[error] Failed tests:
[error] 	org.nd4j.api.RichNDArrayTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 27 s, completed Jul 21, 2015 5:04:32 PM

**Comment by taisukeoe** [comment]
Thanks for reporting. Actually this problem comes from the following issue in nd4j.

https://github.com/deeplearning4j/nd4j/issues/228

As I mentioned at above issue, you can use my workarounded nd4j fork until it's fixed. :)

https://github.com/taisukeoe/nd4j/tree/workarounds

**Comment by rahulpalamuttam** [comment]
ah I see, thanks

**Comment by rahulpalamuttam** [comment]
The nd4s extraction tests continue to fail with the same errors.

**Comment by taisukeoe** [comment]
@rahulpalamuttam 
I haven't faced any problem at current version.
TravisCI also succeeds current latest build and test of nd4s as shown below.
https://travis-ci.org/taisukeoe/nd4s

Would you please confirm if your nd4j and nd4s are the latest?

**Comment by rahulpalamuttam** [comment]
I am seeing the same error as I had originally posted.
I've been running sbt publish - is that equivalent to a clean install?

$ git log
commit e244e053430fcc69c3094356646cfc44e50ef43b
Author: Adam Gibson <adam@skymind.io>
Date:   Tue Jul 21 23:28:57 2015 -0700

    add boolean for mini batch


nd4s rahulsp$ git log

commit 65b09f3fb244c90b6753f1a55e3da552e6f5d590
Merge: 20e6cc6 bd22bdc
Author: Adam Gibson <0@blix.io>
Date:   Wed Jul 22 07:58:02 2015 -0700

    Merge pull request #28 from taisukeoe/ordering
    
    fix #27 / follow ndarray indexing setting change from Fortran to C in nd4j

**Comment by taisukeoe** [comment]
@rahulpalamuttam 
To run sbt test, you don't need `sbt publish`.
Would you do `sbt test` at that nd4s directory?

**Comment by rahulpalamuttam** [comment]
It turns out go be an issue with my git configuration.
I re-cloned the nd4s repo and the tests pass.
Thank you for fixing this!

**Comment by taisukeoe** [comment]
ok, so could you close this issue again? > @rahulpalamuttam @agibsonccc
