### ISSUE TITLE
nd4s slice indexing is off

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#30]
So I've noticed that the nd4s slice indexing is off.
Here is what I mean : 

val nd = Nd4j.create(1d to 8d by 1d toArray, Array(4,2))

which gives me the following array
1.0  2.0  
3.0  4.0  
5.0  6.0  
7.0  8.0

println(nd(0->1, ->))
[[1.0, 2.0]
 [3.0, 4.0]]
* Note that rows 0 and 1 are correctly printed
println
(nd(2->3, ->))

[[3.0, 4.0]
 [5.0, 6.0]]

* However over here rows 1 and 2 are printed when instead it should be rows 3 and 4
when I call nd.getRow(3) it returns the correct row with values [7.0, 8.0]

There are some issues with column indexing as well
I first created the following array
val nd = Nd4j.create(1d to 8d by 1d toArray, Array(2,4))

[[1.0, 2.0, 3.0, 4.0]
 [5.0, 6.0, 7.0, 8.0]]

I am able to correctly print the submatrix (->, 0->1)

[[1.0, 2.0]
 [5.0, 6.0]]

However when I try to printout (->, 2->3) I get an IllegalArgumentException
java.lang.IllegalArgumentException: Unable to get linear index >= 8
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3417)
[info]   at org.nd4j.api.SliceableNDArray$$anonfun$2.apply$mcDI$sp(SliceableNDArray.scala:56)
[info]   at org.nd4j.api.SliceableNDArray$$anonfun$2.apply(SliceableNDArray.scala:56)
[info]   at org.nd4j.api.SliceableNDArray$$anonfun$2.apply(SliceableNDArray.scala:56)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[info]   at org.nd4j.api.SliceableNDArray$class.subMatrix(SliceableNDArray.scala:56)
[info]   ...

**Comment by taisukeoe** [comment]
Thanks for reporting. Fixed in above PR and captured your edge case in test case as follows.

https://github.com/taisukeoe/nd4s/blob/b715711ca632878d1f8b1413e70109d3fe68fdd5/src/test/scala/org/nd4j/api/NDArrayExtractionTest.scala#L42-L84

Plesee be noted that `->` syntax spec has been changed from inclusive to exclusive of closing value.
For example `0->1` in previous version is equivalent with `0->2`.
