### ISSUE TITLE
Runtime error : RangedInt ~ fails to work for dimensions greater than 2

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4s#4]
I received the following error about the following line

    println(indArray(1~2, 2~4))

[info] - testReadMergtoINDArray *** FAILED ***
[info]   java.lang.IllegalStateException: Unable to get number of of rows for a non 2d matrix
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.rows(BaseNDArray.java:3763)
[info]   at org.nd4j.api.Implicits$RichINDArray$.apply$extension(Implicits.scala:36)
[info]   at org.dia.TRMMUtils.MergUtils$Test$$anonfun$2.apply$mcV$sp(MergUtils$Test.scala:19)
[info]   at org.dia.TRMMUtils.MergUtils$Test$$anonfun$2.apply(MergUtils$Test.scala:17)
[info]   at org.dia.TRMMUtils.MergUtils$Test$$anonfun$2.apply(MergUtils$Test.scala:17)
[info]   at org.scalatest.TestRegistration$$anonfun$transformToOutcome$1$$anonfun$apply$1.apply$mcV$sp(TestRegistration.scala:39)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.TestRegistration$$anonfun$transformToOutcome$1.apply(TestRegistration.scala:39)
[info]   at org.scalatest.TestRegistration$$anonfun$transformToOutcome$1.apply(TestRegistration.scala:37)
[info]   ...

indArray is a 3-dimensional array with shape 2, 9000, 3000.

**Comment by taisukeoe** [comment]
Thanks for your feedback.
This PR fixes the problem to extract submatrix of 3 or more dimensional matrix.

https://github.com/deeplearning4j/nd4s/pull/5
