### ISSUE TITLE
Project gives "URI has an authority component" error during compilation.

### ISSUE THREAD

**Issue by mrakgr** [deeplearning4j/nd4s#65]
http://stackoverflow.com/questions/2366270/what-does-uri-has-an-authority-component-mean
Based on the above SO page, this error means that some URLs are malformed. In the logs I see that this might be true. 

Here are the relevant error messages:
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.nd4j#nd4j-api;0.4-rc2.2: several problems occurred while resolving dependency: org.nd4j#nd4j-api;0.4-rc2.2 {compile=[default(compile)]}:
[error] 	several problems occurred while resolving dependency: org.nd4j#nd4j;0.4-rc2.2 {}:
[error] 	URI has an authority component
[error] 	URI has an authority component
[error] 	URI has an authority component
[error] unresolved dependency: org.nd4j#nd4j-jblas;0.4-rc2.2: several problems occurred while resolving dependency: org.nd4j#nd4j-jblas;0.4-rc2.2 {test=[default(compile)]}:
[error] 	several problems occurred while resolving dependency: org.nd4j#nd4j;0.4-rc2.2 {}:
[error] 	URI has an authority component
[error] 	URI has an authority component
[error] 	URI has an authority component
[error] unresolved dependency: ch.qos.logback#logback-classic;1.1.3: several problems occurred while resolving dependency: ch.qos.logback#logback-classic;1.1.3 {test=[default(compile)]}:
[error] 	several problems occurred while resolving dependency: ch.qos.logback#logback-parent;1.1.3 {}:
[error] 	URI has an authority component
[error] 	URI has an authority component
[error] 	URI has an authority component

In my case I have 0.4-rc1.2 version of the libraries on my computer and I don't even see 0.4-rc2.2 on Maven Central so this might be a mistake in URL, but I do not have a clue as to why ch.qos.logback failed.

**Comment by taisukeoe** [comment]
Would you please share more detail about environment?
Similar error occurs in sbt or typesafe-activator in Windows as follows. If that's a case, below link might help you.

http://stackoverflow.com/questions/30710316/intellij-and-sbt-0-13-5-uri-has-an-authority-component
http://stackoverflow.com/questions/30624099/sbt-0-13-8-uri-has-an-authority-component

As shown below, nd4s is already published to proper URL and it works well in my environment (Mac, sbt 0.13.8).  
http://repo1.maven.org/maven2/org/nd4j/nd4s_2.11/

**Comment by mrakgr** [comment]
As per your advice, I opened the build.sbt in Wordpad and changed the "file://" to "file:///". Now it works fine, all tests passed. I am trying to run this on WIndows 10. Just installed IntelliJ, Scala and Sbt yesterday, so they are all set to defaults. The error also occurred to me previously when I tried to run it directly from the command line using Sbt fresh after installing it.

Right now I am trying to figure out how to use nd4s in my Scala project. I've extracted it to hard drive and tried adding it as a global library in IntelliJ, but it is not going as planned. It has been a while since I used Scala, but this still beats trying to learn a whole new OS in order to try a DL library. Any advice would be appreciated.

**Comment by taisukeoe** [comment]
> As per your advice, I opened the build.sbt in Wordpad and changed the "file://" to "file:///". Now it works fine, all tests passed. 

Glad to hear that.

> I realized that I needed to publish the project in order to use it, first time I heard about it, so I ran "sbt +publish-local". 

No, you don't need to. It's already under maven central so you don't need to do `+publish-local` to try ND4S any more unless you'll want to latest master.

Since your original problem is already solved, let me close this issue.
If you need any help, would you come to gitter channel (which I've created right now)?

https://gitter.im/deeplearning4j/nd4s
