### ISSUE TITLE
NDArray method rowP returns incorrect result

### ISSUE THREAD

**Issue by alexland** [deeplearning4j/nd4s#69]
the example in the README is:
```Scala
for (row <- arr.rowP if row.get(0) > 1 yield row * 2
```
the result from this expression (in same row in the table in the README) is:
```Scala
 [[1.0, 2.0, 3.0]
  [8.0, 10.0, 12.0]
  [14.0, 16.0, 18.0]]
```
ie, all three rows in the original array, element-wise multiplied by 2

the expression ought to return:

```Scala
 [[8.00,10.00,12.00]
 [14.00,16.00,18.00]]
```

reason (obvious):

the guard

```Scala
if row.get(0) > 1
```

row.get(0) just returns the first element in each row in the array, arr, the expression at the top just _for each row in arr, if the value at the first offset is greater than 1, multiply each element in the row by two and yield it._

so the guard should cause the first row to be filtered out--so the expression ought to return just *2* rows from the original array (w/ all elements multipled by 2—i.e.,, but it does not, it returns *all three* original rows

i have found  the relevant lines in the source; a trivial fix so i'm happy to submit a patch myself, just let me know

**Comment by taisukeoe** [comment]
Since I couldn't find your PR, I fixed this incidentally.
Please feel free to elaborate me if needed. Thanks for your contribution!
