### ISSUE TITLE
ND4S example in nd4j.org doesn't use ND4S at all.

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4s#80]
It has to be fixed, or removed.

http://nd4j.org/scala.html

**Comment by chrisvnicholson** [comment]
Oe-san - Can you replace the examples with ND4S code? Please just go to this page, edit it and submit a pull request, which I will accept: https://github.com/deeplearning4j/nd4j/blob/gh-pages/scala.md

**Comment by taisukeoe** [comment]
Thanks, I will do it.
