### ISSUE TITLE
ND4S 2.11 overloaded method value + with alternatives

### ISSUE THREAD

**Issue by JohnTheDang** [deeplearning4j/nd4s#83]
When running the code at http://nd4j.org/scala.html the program gives the error message 
Error:(33, 31) overloaded method value + with alternatives:
  (that: org.nd4j.linalg.api.complex.IComplexNumber)org.nd4j.linalg.api.complex.IComplexNDArray <and>
  [B](that: Number)(implicit ev: org.nd4s.NDArrayEvidence[org.nd4j.linalg.api.ndarray.INDArray,B])org.nd4j.linalg.api.ndarray.INDArray <and>
  [B](that: org.nd4j.linalg.api.ndarray.INDArray)(implicit ev: org.nd4s.NDArrayEvidence[org.nd4j.linalg.api.ndarray.INDArray,B])org.nd4j.linalg.api.ndarray.INDArray
 cannot be applied to (String)
    println(Nd4j.sum(arr4, 0) + "Calculate the sum for each row")
                              ^

for every + in println

**Comment by taisukeoe** [comment]
Thanks for reporting. Fixed.
