### ISSUE TITLE
Nd4s Sparse

### ISSUE THREAD

**Issue by asevans48** [deeplearning4j/nd4s#86]
Any idea if there will be a sparse implementation? There is jCuSparse and sparse BLAS [http://math.nist.gov/spblas/]. Any idea if it will include the same matrix operations as those available in scipy?

**Comment by taisukeoe** [comment]
@asevans48 
Since ND4S provides Scala syntax layer of ND4J, It would be better to support it after ND4J supports it.

Here is an issue of ND4J about sparse matrix.
https://github.com/deeplearning4j/nd4j/issues/66

**Comment by raver119** [comment]
Sparse support is on our roadmap: http://deeplearning4j.org/roadmap.html

**Comment by asevans48** [comment]
I've started some sparse support on my own. Glad to see it in the roadmap. So far I have  a working CSC matrix using arrays and an ND4J array but nothign in cuSparse yet.

**Comment by agibsonccc** [comment]
@asevans48 We'd love to get this up and running in a pull request.

**Comment by agibsonccc** [comment]
We are implementing sparse in nd4j soon.

**Comment by gsaxena888** [comment]
how "soon" is soon? @agibsonccc

**Comment by agibsonccc** [comment]
it's being worked on now but don't expect it for a few months. This isn't something we can just snap our fingers and make happen instantly.

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5257
