### ISSUE TITLE
Issues while compiling example on http://nd4j.org/scala.html

### ISSUE THREAD

**Issue by kykamath** [deeplearning4j/nd4s#88]
I was looking at the example of how to use nd4j in scala on http://nd4j.org/scala.html. While trying the example at the bottom I started getting a compiler error for this line: "arr += arr2", and a few others. I was using scala 2.10.4

After discussing this issue with agibsonccc, I was able to compile correctly and run the program. Here were the issues:
- missing import for "org.nd4s.Implicits._"
- "+" operator overriding was causing issues with println. I had to explicitly convert all INDArray objects to string using toString in println.

Here is the gist of code that compiled correctly: https://gist.github.com/kykamath/076028d46de956dc1383

**Comment by taisukeoe** [comment]
Duplicated with https://github.com/deeplearning4j/nd4s/issues/83 ?

**Comment by taisukeoe** [comment]
Actually ND4S example in nd4j.org at this moment is not actually ND4S as written below.
https://github.com/deeplearning4j/nd4s/issues/80

Please refer to cheatsheet in README about how-to-use at this moment.
