### ISSUE TITLE
Collection-like Ops are not working.

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4s#91]
testing with ND4J 0.4-rc3.9 in feature/0.4-rc3.9 branch

```
[info] NDArrayCollectionAPITest:
[info] CollectionLikeNDArray
[info] - should provides filter API *** FAILED ***
[info]   [[1.00, 2.00, 3.00],
[info]    [4.00, 5.00, 6.00],
[info]    [7.00, 8.00, 9.00]] did not equal [[0.00, 0.00, 0.00],
[info]    [4.00, 5.00, 6.00],
[info]    [7.00, 8.00, 9.00]] (NDArrayCollectionAPITest.scala:17)
[info] - should provides filter bitmask API *** FAILED ***
[info]   [[1.00, 2.00, 3.00],
[info]    [4.00, 5.00, 6.00],
[info]    [7.00, 8.00, 9.00]] did not equal [[0.00, 1.00, 0.00],
[info]    [1.00, 0.00, 1.00],
[info]    [0.00, 1.00, 0.00]] (NDArrayCollectionAPITest.scala:34)
[info] - should provides map API *** FAILED ***
[info]   [[1.00, 2.00, 3.00],
[info]    [4.00, 5.00, 6.00],
[info]    [7.00, 8.00, 9.00]] did not equal [[ 3.00,  5.00,  7.00],
[info]    [ 9.00, 11.00, 13.00],
[info]    [15.00, 17.00, 19.00]] (NDArrayCollectionAPITest.scala:51)
```

**Comment by DaveDeCaprio** [comment]
are there any workarounds or stats on this?

**Comment by DaveDeCaprio** [comment]
I'm seeing this same issue with 5.0.0
println((1 to 9).toNDArray.map(_ + 0.5))
prints
[1.00, 2.00, 3.00, 4.00, 5.00, 6.00, 7.00, 8.00, 9.00]

**Comment by agibsonccc** [comment]
@DaveDeCaprio I don' have developers to put on this right now. You are welcome to send us a pull request.

**Comment by saudet** [comment]
@DaveDeCaprio nd4j doesn't support custom ops written in Java (bytecode) anymore so it's unclear how we should support those operations for now.

**Comment by DaveDeCaprio** [comment]
Thanks, yes I looked at fixing the issue but pretty quickly  it became clear this was not a minor bug.

I have a library of primitives for doing very fast off heap computations in Scala.  It uses specialization and a few other tricks to allow you to program functionally in Scala, but removing nearly all the overhead.  I've used it with (your) JavaCV library.  I may try to port it over to work with Nd4s.

**Comment by agibsonccc** [comment]
Hey folks, we've largely decided not to support this for now. You can use boolean indexing and all of the masking operations. A large problem with the "map" operation is it's operating on 1: mutable objects. and 2: you're trying to change sizes. NDarrays aren't lists and shouldn't be treated as such.
You are welcome to propose something new maybe on top of the op executioner..but we should try to be a bit more specific about the apis.

**Comment by javadba** [comment]
@agibsonccc    I "get" that the shape can not change: that's reasonable. But .. **disallowing one to one** map operations?  This is a *fatal* flaw in usability of this library. 

I am a heavy numpy user but my heart is with scala. I had thought that maybe nd4j/s were maybe mature enough : but the point of using scala (and the associated cost of moving away from numpy/scikit learn) is exactly the ability to do these transformations.   

Can you point out where this could be fixed?  Again *just for 1-1 mapping*.

**Comment by saudet** [comment]
It needs to be fixed in libnd4j, by allowing callbacks from C++. It's something that is planned, but not started yet. If you feel comfortable with C++ and would like to give it a try, let us know and we'll provide guidance!
