### ISSUE TITLE
Instead of using custom -> for ranges, use ones that are already built into Scala

### ISSUE THREAD

**Issue by Mocuto** [deeplearning4j/nd4s#95]
As the title states, currently the documentation shows the following:
`arr(0 -> 3)` in ND4S is equivalent to `arr[0:3]` in Numpy+Python

However, Scala already has its own syntax that is equivalent to `arr[0:3]` in Python, which is `arr(x until y)`
In order to align more with Scala, ND4S should simply have
`arr(0 until 3)` as being equivalent to `arr[0:3]` in Python,

 and removing the `x->y` syntax entirely, as in Scala using the `until` keyword is more intuitive and using `->` is more associated with Maps/Tuples, which makes it confusing.

**Comment by javadba** [comment]
No let's keep this: the enhanced similarity to numpy is appreciated. The scala syntax is clumsy.

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5258
